version: 2
jobs:
  build:
    working_directory: ~/analytics.js-react-quickstart
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npm run build
